/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: makoto (https://sketchfab.com/lu87813)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/air-jordan-1-a4b434181fbb48008ad460722fd53725
Title: Air Jordan 1
*/

"use client";

import * as THREE from 'three';
import { GLTF } from 'three-stdlib';
import { CameraControls, Plane, useGLTF, useScroll } from "@react-three/drei";
import { useLayoutEffect, useRef } from "react";
import { ScrollTrigger } from "gsap/ScrollTrigger";
//import { useControls } from "leva";
import { useThree } from "@react-three/fiber";
import gsap from "gsap";
import { useGSAP } from '@gsap/react';

gsap.registerPlugin(ScrollTrigger, useGSAP);

type GLTFResult = GLTF & {
  nodes: {
    shoe_shoe_0: THREE.Mesh
    shoelace_shoelace_0: THREE.Mesh
  }
  materials: {
    shoe: THREE.MeshStandardMaterial
    shoelace: THREE.MeshStandardMaterial
  }
}

// Source : https://sketchfab.com/3d-models/air-jordan-1-a4b434181fbb48008ad460722fd53725
export const Jordan = ({ ...props }) => {
  const { nodes, materials } = useGLTF("/air_jordan_1.glb") as unknown as GLTFResult;
  const jordans = useRef<THREE.Group>(null!);

  const { scene, camera } = useThree();
  //const tl = gsap.timeline();

  // ----- used for getting the position for the shoes ----
  // const { cameraPosition, scenePosition, sceneRotation } = useControls({
  // 	cameraPosition: {
  // 		value: {
  // 			x: 5,
  // 			y: 4,
  // 			z: 2.8,
  // 		},
  // 		step: 0.05,
  // 	},
  // 	scenePosition: {
  // 		value: { x: 3.01, y: 0.76, z: 3.7 },
  // 		step: 0.05,
  // 	},

  // 	sceneRotation: {
  // 		value: { x: -0.53, y: -3.48, z: -0.21 },
  // 		step: 0.01,
  // 	},
  // });

  useGSAP(() => {
    if (!jordans.current) return;
    new ScrollTrigger({});
    const t1 = gsap.timeline();
    // component About.tsx
    t1.to(camera.position, {
      x: 5,
      y: 4.0,
      z: 2.8,
      scrollTrigger: {
        trigger: ".second-section",
        start: "top bottom",
        end: "top top",
        scrub: true,
        immediateRender: false,
      },
    })
      .to(scene.position, {
        x: 3.01,
        y: 0.76,
        z: 3.7,
        scrollTrigger: {
          trigger: ".second-section",
          start: "top bottom",
          end: "top top",
          scrub: true,
          immediateRender: false,
        },
      })
      .to(scene.rotation, {
        x: -0.53,
        y: -3.48,
        z: -0.21,
        scrollTrigger: {
          trigger: ".second-section",
          start: "top bottom",
          end: "top top",
          scrub: true,
          immediateRender: false,
        },
      })
      // component - BuyNow.tsx
      .to(camera.position, {
        x: 5,
        y: 3.8,
        z: 2.8,
        scrollTrigger: {
          trigger: ".third-section",
          start: "top bottom",
          end: "top top",
          scrub: true,
          immediateRender: false,
        },
      })
      .to(scene.position, {
        x: 2.31,
        y: 0.01,
        z: -0.7,
        scrollTrigger: {
          trigger: ".third-section",
          start: "top bottom",
          end: "top top",
          scrub: true,
          immediateRender: false,
        },
      })
      .to(scene.rotation, {
        x: 0.67,
        y: -12.9,
        z: 0.79,
        scrollTrigger: {
          trigger: ".third-section",
          start: "top bottom",
          end: "top top",
          scrub: true,
          immediateRender: false,
        },
      });
  }, []);

  // ---- used for debug ----
  // useFrame(() => {
  // 	camera.position.x = cameraPosition.x;
  // 	camera.position.y = cameraPosition.y;
  // 	camera.position.z = cameraPosition.z;
  // 	scene.position.x = scenePosition.x;
  // 	scene.position.y = scenePosition.y;
  // 	scene.position.z = scenePosition.z;
  // 	scene.rotation.x = sceneRotation.x;
  // 	scene.rotation.y = sceneRotation.y;
  // 	scene.rotation.z = sceneRotation.z;
  // });

  return (
    <>
      <directionalLight
        castShadow
        position={[-2.38, 1.32, 0.74]}
        intensity={5}
      />
      <ambientLight intensity={0.5} />
      <group
        ref={jordans}
        position={[2, 1, -1]}
        castShadow
        scale={0.1}
        {...props}
        dispose={null}
      >
        <mesh
            castShadow
            receiveShadow
            geometry={nodes.shoe_shoe_0.geometry}
            material={materials.shoe}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={100}
        />
        <mesh
            castShadow
            receiveShadow
            geometry={nodes.shoelace_shoelace_0.geometry}
            material={materials.shoelace}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={100}
        />
      </group>
    </>
  );
};