
'use client';
/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/
import * as THREE from 'three';
import { GLTF } from 'three-stdlib';
import { useEffect, useMemo, useState } from 'react';
import debounce from 'lodash/debounce';
import { useGLTF, useEnvironment, Text } from '@react-three/drei';
import { Select } from '@react-three/postprocessing';
import Price from './Price';
import { ThreeEvent } from '@react-three/fiber';
import type { JSX } from 'react';

/** Literal names you use in the UI/hover tooltips */
type HoveredName =
  | 'BRÖNDEN'
  | 'VOXLÖV'
  | 'LIVSVERK VASE'
  | 'SKAFTET LAMP'
  | 'FANBYN CHAIR';

type GLTFResult = GLTF & {
  nodes: {
    walls_1: THREE.Mesh;
    walls_2: THREE.Mesh;
    carpet: THREE.Mesh;
    table: THREE.Mesh;
    kitchen: THREE.Mesh;
    vase: THREE.Mesh;
    lamp_socket: THREE.Mesh;
    sink: THREE.Mesh;
    vase1: THREE.Mesh;
    chairs_1: THREE.Mesh;
    chairs_2: THREE.Mesh;
    plant_1: THREE.Mesh;
    plant_2: THREE.Mesh;
    bottle: THREE.Mesh;
    cuttingboard: THREE.Mesh;
    lamp: THREE.Mesh;
    lamp_cord: THREE.Mesh;
    bowl: THREE.Mesh;
  };
  materials: {
    floor: THREE.MeshStandardMaterial;
    walls: THREE.MeshStandardMaterial;
    carpet: THREE.MeshStandardMaterial;
    gray: THREE.MeshStandardMaterial;
    chrome: THREE.MeshStandardMaterial;
    plastic: THREE.MeshStandardMaterial;
    potted_plant_01_leaves: THREE.MeshStandardMaterial;
    potted_plant_01_pot: THREE.MeshStandardMaterial;
    glass: THREE.MeshStandardMaterial;
  };
};

/** Map of prices; 'KNOXHULT' is the default display when nothing is hovered */
const PRICES: Record<HoveredName | 'KNOXHULT', number> = {
  KNOXHULT: 5999,
  BRÖNDEN: 433,
  SKAFTET: 77, // if you want the label to show 'SKAFTET LAMP', either add that key or map it below
  'SKAFTET LAMP': 77,
  FANBYN: 255, // same here if you use 'FANBYN CHAIR'
  'FANBYN CHAIR': 255,
  VOXLÖV: 1699,
  LIVSVERK: 44, // if you use 'LIVSVERK VASE' in the UI, include that key:
  'LIVSVERK VASE': 44,
};

export function Scene(props: JSX.IntrinsicElements['group']) {
  // Load model with strong typing for nodes/materials
  const { nodes, materials } = useGLTF('/kitchen-transformed.glb') as unknown as GLTFResult;
  // (Optional) Environment map; you mentioned chairs reflections in comments.
  // Keep this to apply envMap to selected materials if desired.
  const env = useEnvironment({ preset: 'city' });
  // Hover state is a specific set of strings or null
  const [hovered, setHovered] = useState<HoveredName | null>(null);
  // Debounce hover updates to prevent noisy re-renders
  const debouncedHover = useMemo(() => {
    // Keep the debounced wrapper sync; call setState inside it
    return debounce((name: HoveredName | null) => {
      setHovered(name);
    }, 30);
  }, []);

  // Important: cancel pending debounced calls on unmount
  useEffect(() => {
    return () => debouncedHover.cancel();
  }, [debouncedHover]);

  // Typed over/out handlers usable on <Select />
  const over = (name: HoveredName) =>
    (e: ThreeEvent<PointerEvent>): void => {
      e.stopPropagation();
      debouncedHover(name);
    };
  const out = (e: ThreeEvent<PointerEvent>): void => {
    e.stopPropagation();
    debouncedHover(null);
  };

  // Compute the price; fall back to KNOXHULT when nothing hovered
  const price = hovered ? PRICES[hovered] : PRICES['KNOXHULT'];

  return (
    <>
      <group {...props} dispose={null}>
        <Select enabled={hovered === 'BRÖNDEN'} onPointerOver={over('BRÖNDEN')} onPointerOut={out}>
          <mesh geometry={nodes.carpet.geometry} material={materials.carpet} />
        </Select>
        <Select enabled={hovered === 'VOXLÖV'} onPointerOver={over('VOXLÖV')} onPointerOut={out}>
          <mesh geometry={nodes.table.geometry} material={materials.walls} />
        </Select>
        <mesh geometry={nodes.kitchen.geometry} material={materials.walls} />
        <Select enabled={hovered === 'LIVSVERK VASE'} onPointerOver={over('LIVSVERK VASE')} onPointerOut={out}>
          <mesh geometry={nodes.vase.geometry} material={materials.gray} />
        </Select>
        <mesh geometry={nodes.sink.geometry} material={materials.chrome} />
        <mesh geometry={nodes.vase1.geometry} material={materials.gray} />
        <mesh geometry={nodes.bottle.geometry} material={materials.glass} />
        <mesh geometry={nodes.cuttingboard.geometry} material={materials.walls} />
        <Select
          enabled={hovered === 'SKAFTET LAMP'}
          onPointerOver={over('SKAFTET LAMP')}
          onPointerOut={out}
        >
          <mesh geometry={nodes.lamp_socket.geometry} material={materials.gray} />
          <mesh geometry={nodes.lamp.geometry} material={materials.gray} />
          <mesh geometry={nodes.lamp_cord.geometry} material={materials.gray} />
        </Select>
        <mesh geometry={nodes.bowl.geometry} material={materials.walls} />
        <mesh geometry={nodes.walls_1.geometry} material={materials.floor} />
        <mesh geometry={nodes.walls_2.geometry} material={materials.walls} />
        <Select
          enabled={hovered === 'FANBYN CHAIR'}
          onPointerOver={over('FANBYN CHAIR')}
          onPointerOut={out}
        >
          <mesh geometry={nodes.chairs_1.geometry} material={materials.walls} />
          <mesh geometry={nodes.chairs_2.geometry} material={materials.plastic} />
        </Select>
        <mesh geometry={nodes.plant_1.geometry} material={materials.potted_plant_01_leaves} />
        <mesh geometry={nodes.plant_2.geometry} material={materials.potted_plant_01_pot} />
      </group>
      <Text position={[1, 1.25, 0]} color="black" fontSize={0.15} font="Inter-Regular.woff" letterSpacing={-0.05}>
        {hovered ?? 'KNOXHULT'}
      </Text>
      {/* Forward the price to the ticker component */}
      <Price value={price} position={[-2, 0.3, -3.25]} />
    </>
  );
}

// Ensure drei caches the GLB
useGLTF.preload('/kitchen-transformed.glb');

export default Scene;

