var trip_data = [
  {"lat" : 55.859234, 
   "lon" : -4.244489, 
   "name" : "Glasgow, Scotland",
   "country" : "826",
   "posts" : {
   	"NoStory" : ""
   }},
   {"lat" : 55.950448, 
   "lon" : -3.180290, 
   "name" : "Edinburgh, Scotland",
   "country" : "826",
   "posts" : {
   	"NoStory" : ""
   }},
   {"lat" : 56.241301, 
   "lon" : -4.700753, 
   "name" : "Loch Lomond, Scotland",
   "country" : "826",
   "posts" : {
   	"NoStory" : ""
   }},
  {"lat" : 48.215567, 
   "lon" : 16.354645, 
   "name" : "Vienna, Austria",
   "country" : "040",
   "posts" : {
   	"NoStory" : ""
   }},
  {"lat" : 59.335523, 
   "lon" : 14.076803, 
   "country" : "752",
   "name" : "Stockholm, Sweden",
   "posts" : {
   	"NoStory" : ""
   }},
  {"lat" : 68.349822, 
   "lon" : 18.829744,
   "name" : "Abisko, Sweden",
   "country" : "752",
   "posts" : {
   "Nature" : "https://twosundowners.com/fjallraven_classic/",
   "Gallery" : "https://twosundowners.com/photo-gallery/gallery/fjallraven-classic-sweden/#album"}},
  {"lat" : 68.229271, 
   "lon" : 12.223273,
   "name" : "Lofoten, Norway",
   "country" : "578",
   "posts" : {
   "Nature": "https://twosundowners.com/lofoten/",
   "Gallery" : "https://twosundowners.com/photo-gallery/gallery/lofoten/#album"}},
  {"lat" : 49.220593, 
   "lon" : 18.725948, 
   "name" : "Zilina, Slovakia",
   "country" : "703",
   "posts" : {"Gallery" : "https://twosundowners.com/photo-gallery/gallery/slovakia/#album"}},
  {"lat" : 48.769299, 
   "lon" : 17.866317, 
   "name" : "Zelena Voda, Slovakia",
   "country" : "703",
   "posts" : {
   "Climbing" : "https://twosundowners.com/climbing-slovakia/",
   "Gallery" : "https://twosundowners.com/photo-gallery/gallery/slovakia/#album"}},
  {"lat" : 49.089275,
   "lon" : 19.608975, 
   "name" : "Liptovsky Mikulas, Slovakia",
   "country" : "703",
   "posts" : {
   "Climbing" : "https://twosundowners.com/climbing-slovakia/",
   "Running" : "https://twosundowners.com/slovak-running/",
   "Gallery" : "https://twosundowners.com/photo-gallery/gallery/slovakia/#album"}},
  {"lat" : 48.964045,
   "lon" : 20.385249, 
   "name" : "Podlesok, Slovakia",
   "country" : "703",
   "posts" : 
   {"Climbing" : "https://twosundowners.com/climbing-slovakia/",
   "Running" : "https://twosundowners.com/slovak-running/",
   "Gallery" : "https://twosundowners.com/photo-gallery/gallery/slovakia/#album"}},
  {"lat" : 47.662625,
   "lon" : 23.558505,
   "name" : "Baia Mare, Romania",
   "country" : "642",
   "posts" : {
   "Climbing" : "https://twosundowners.com/climbing-in-romania/"}},
  {"lat" : 46.779538,
   "lon" : 23.608950, 
   "name" : "Cluj-Napoca, Romania",
   "country" : "642",
   "posts" : {
   "Climbing" : "https://twosundowners.com/climbing-in-romania/",
   "City" : "https://twosundowners.com/cluj/",
   "Food" : "https://twosundowners.com/cluj/",
   "Gallery" : "https://twosundowners.com/photo-gallery/gallery/baia-mare/#album"}},
  {"lat" : 46.217893,
   "lon" : 24.788900, 
   "name" : "Sighisoara, Romania",
   "country" : "642",
   "posts" : {"Gallery" : "https://twosundowners.com/photo-gallery/gallery/sighisoara/#album"}
   },
  {"lat" : 45.514474, 
   "lon" : 25.367078, 
   "name" : "Bran, Romania",
   "country" : "642",
   "posts" : {
   "Climbing" : "https://twosundowners.com/climbing-in-romania/"}},
  {"lat" : 45.652937, 
   "lon" : 25.602984, 
   "name" : "Brasov, Romania",
   "country" : "642",
   "posts" : {
   "General" : "https://twosundowners.com/road-to-bulgaria/",
   "Climbing" : "https://twosundowners.com/climbing-in-romania/",
   "Gallery" : "https://twosundowners.com/photo-gallery/gallery/road-to-bulgaria/#album"}},
  {"lat": 45.535054, 
   "lon": 25.218013,
   "name": "Piatra Craiului, Romania",
   "country" : "642",
   "posts" : 
   {"Nature": "https://twosundowners.com/piatra-craiului/",
   "Climbing" : "https://twosundowners.com/climbing-in-romania/",
   "Gallery" : "https://twosundowners.com/photo-gallery/gallery/piatra-craiului/#album"}},
  {"lat" : 45.498800, 
   "lon" : 25.578403, 
   "name" : "Predeal, Romania",
   "country" : "642",
   "posts" : {
   "General" : "https://twosundowners.com/road-to-bulgaria/",
   "Gallery" : "https://twosundowners.com/photo-gallery/gallery/road-to-bulgaria/#album"}},
  {"lat" : 44.435779, 
   "lon" : 26.097375, 
   "name" : "Bucharest, Romania",
   "country" : "642",
   "posts" : {
   "General" : "https://twosundowners.com/road-to-bulgaria/",
   "City" : "https://twosundowners.com/road-to-bulgaria/",
   "Climbing" : "https://twosundowners.com/climbing-in-romania/",
   "Gallery" : "https://twosundowners.com/photo-gallery/gallery/road-to-bulgaria/#album"}},
  {"lat" : 43.077798,
   "lon" : 25.629002, 
   "name" : "Veliko Tarnovo, Bulgaria",
   "country" : "100",
   "posts" : {
   "City": "https://twosundowners.com/veliko-tarnovo/",
   "Nature": "https://twosundowners.com/veliko-tarnovo/",
   "Running": "https://twosundowners.com/veliko-tarnovo/",
   "Food": "https://twosundowners.com/veliko-tarnovo/",
   "Gallery" : "https://twosundowners.com/photo-gallery/gallery/veliko-tarnovo/#album"}},
  {"lat" : 43.175791, 
   "lon" : 24.073860, 
   "name" : "Prohodna Cave, Bulgaria",
   "country" : "100",
   "posts" : {
   "Gallery" : "https://twosundowners.com/photo-gallery/gallery/prohodna-cave-karlukovo/#album"}},
  {"lat" : 43.627028,
   "lon" : 22.679694, 
   "name" : "Belogradchik, Bulgaria",
   "country" : "100",
   "posts" : {
   "General" : "https://twosundowners.com/belogradchik-vratsa/",
   "Gallery" : "https://twosundowners.com/photo-gallery/gallery/vratsa-belogradchik/#album"}},
  {"lat" : 43.213010,
   "lon" : 23.546738, 
   "name" : "Vratsa, Bulgaria",
   "country" : "100",
   "posts" : {
   "General" : "https://twosundowners.com/belogradchik-vratsa/",
   "Gallery" : "https://twosundowners.com/photo-gallery/gallery/vratsa-belogradchik/#album"}},
  {"lat" : 42.705439,
   "lon" : 23.297158, 
   "name" : "Sofia, Bulgaria",
   "country" : "100",
   "posts" : {
   "City" : "https://twosundowners.com/sofia/",
   "Guide" : "https://twosundowners.com/sofia/",
   "Food" : "https://twosundowners.com/sofia/",
   "Gallery" : "https://twosundowners.com/photo-gallery/gallery/sofia/#album"}},
  {"lat" : 42.133314, 
   "lon" : 23.549659, 
   "name" : "Rila, Bulgaria",
   "country" : "100",
   "posts" : {
   "Nature" : "https://twosundowners.com/rila/",
   "Gallery" : "https://twosundowners.com/photo-gallery/gallery/rila-mountains/#album"}},
  {"lat" : 42.271949,
   "lon" : 23.604295, 
   "name" : "Borovets, Bulgaria",
   "country" : "100",
   "posts" : {
   "Nature" : "https://twosundowners.com/rila/",
   "Gallery" : "https://twosundowners.com/photo-gallery/gallery/rila-mountains/#album"}},
  {"lat" : 42.146136,
   "lon" : 24.741558, 
   "name" : "Plovdiv, Bulgaria",
   "country" : "100",
   "posts" : {
   "City" : "https://twosundowners.com/plovdiv/",
   "Running" : "https://twosundowners.com/plovdiv/",
   "Gallery" : "https://twosundowners.com/photo-gallery/gallery/plovdiv/#album"}},
  {"lat" : 41.838192,
   "lon" : 23.492494, 
   "name" : "Bansko, Bulgaria",
   "country" : "100",
   "posts" : {
   "Running" : "https://twosundowners.com/bansko/",
   "General" : "https://twosundowners.com/bansko/",
   "Gallery" : "https://twosundowners.com/photo-gallery/gallery/bansko/#album"}},
  {"lat" : 41.940874,
   "lon" : 21.304953, 
   "name" : "Matka Canyon, Macedonia",
   "country" : "807",
   "posts" : {
   "Nature" : "https://twosundowners.com/skopje/",
   "Gallery" : "https://twosundowners.com/photo-gallery/gallery/skopje/#album"}},
  {"lat" : 42.005702,
   "lon" : 21.435874, 
   "name" : "Skopje, Macedonia",
   "country" : "807",
   "posts" : {
   "City" : "https://twosundowners.com/skopje/",
   "Gallery" : "https://twosundowners.com/photo-gallery/gallery/skopje/#album"}},
  {"lat" : 42.217693,
   "lon" : 20.721379,
   "name" : "Prizren, Kosovo", 
   "country" : "-99",
   "posts" : {
   "City" : "https://twosundowners.com/prizren/"}},
  {"lat" : 42.450726,
   "lon" : 19.889191,
   "name" : "Valbone Valley, Albania",
   "country" : "008",
   "posts" : {
   "Nature" : "https://twosundowners.com/valbone-valley/",
   "Running" : "https://twosundowners.com/valbone-valley/",
   "Food" : "https://twosundowners.com/valbone-valley/",
   "Gallery" : "https://twosundowners.com/photo-gallery/gallery/valbone-valley/#album"}},
  {"lat" : 42.058600,
   "lon" : 19.505837,
   "name" : "Shkodra, Albania",
   "country" : "008",
   "posts" : {
   "City" : "https://twosundowners.com/albania/",
   "Gallery" : "https://twosundowners.com/photo-gallery/gallery/mask-factory-shkodra/#album"}},
  {"lat" : 42.424350,
   "lon" : 18.771442,
   "name" : "Kotor, Montenegro",
   "country" : "499",
   "posts" : {
   "City" : "https://twosundowners.com/montenegro/",
   "Running" : "https://twosundowners.com/montenegro/",
   "Gallery" : "https://twosundowners.com/photo-gallery/gallery/montenegro/#album"}},
  {"lat" : 42.289454,
   "lon" : 18.841132,
   "name" : "Budva, Montenegro",
   "country" : "499",
   "posts" : {
   "City" : "https://twosundowners.com/montenegro/",
   "Gallery" : "https://twosundowners.com/photo-gallery/gallery/montenegro/#album"}},
  {"lat" : 42.205771,
   "lon" : 18.945038, 
   "name" : "Petrovac, Montenegro",
   "country" : "499",
   "posts" : {
   "Running" : "https://twosundowners.com/montenegro/",
   "Gallery" : "https://twosundowners.com/photo-gallery/gallery/montenegro/#album"}},
  {"lat" : 42.654811,
   "lon" : 18.104529,
   "name" : "Dubrovnik, Croatia",
   "country" : "191",
   "posts" : {
   "City" : "https://twosundowners.com/dubrovnik/",
   "Guide" : "https://twosundowners.com/dubrovnik/",
   "Gallery" : "https://twosundowners.com/photo-gallery/gallery/dubrovnik/#album"}},
  {"lat" : 43.346918, 
   "lon" : 17.809567, 
   "name" : "Mostar, Bosna & Herzegovina",
   "country" : "070",
   "posts" : {
   "City" : "https://twosundowners.com/week-bosnia-herzegovina/",
   "Running" : "https://twosundowners.com/week-bosnia-herzegovina/",
   "Gallery" : "https://twosundowners.com/photo-gallery/gallery/bosnia-and-herzegowina/#album"}},
  {"lat" : 43.858000,
   "lon" : 18.382982,
   "name" : "Sarajevo, Bosna & Herzegovina",
   "country" : "070",
   "posts" : {
   "City" : "https://twosundowners.com/week-bosnia-herzegovina/"}},
  {"lat" : 48.734575, 
   "lon" : 9.314098, 
   "name" : "Esslingen, Germany",
   "country" : "276",
   "posts" : {
   	"NoStory" : ""
   }},
  {"lat" : 47.070191, 
   "lon" : 14.300150, 
   "name" : "Sankt Lambrecht, Austria",
   "country" : "040",
   "posts" : {
   	"NoStory" : ""
   }},
  {"lat" : 28.458773, 
  "lon" : -81.390048, 
  "name" : "Orlando, FL", 
  "country" : "840",
  "posts" : {
  "General": "https://twosundowners.com/journey-to-lima/"}},
  {"lat" : -12.133251,
   "lon" : -77.028710,
    "name" : "Lima, Peru",
    "country" : "604",
    "posts" : {
    "Food" : "https://twosundowners.com/vegetarian-Guide-lima/",
    "Guide" : "https://twosundowners.com/peru-car-rental/",
    "Guide" : "https://twosundowners.com/one-month-in-lima/"}},
  {"lat" : -13.838349,
   "lon" : -76.250924,
    "name" : "Paracas, Peru",
    "country" : "604",
    "posts" : {
    "Nature" : "https://twosundowners.com/paracas/",
    "Guide" : "https://twosundowners.com/paracas/",
    "Gallery" : "https://twosundowners.com/photo-gallery/gallery/paracas-peru/#album"}},
  {"lat" : -14.087867,
   "lon" : -75.764877,
    "name" : "La Huacachina, Peru",
    "country" : "604",
    "posts" : {
    "Guide" : "https://twosundowners.com/la-huacachina-sandy-paradise-foreigners/"}},
  {"lat" : -16.490746, 
   "lon" : -68.143358, 
   "name" : "La Paz, Bolivia",
   "country" : "068",
   "posts" : {
   	"Guide" : "https://twosundowners.com/la-paz-10-things/",
   	"Food" : "https://twosundowners.com/vegetarians-guide-la-paz/",
   	"Running" : "https://twosundowners.com/bolivia-running/"
   	}},
  {"lat" : -20.337464, 
   "lon" : -67.570242, 
   "name" : "Salar de Uyuni, Bolivia",
   "country" : "068",
   "posts" : {
   	"General" : "https://twosundowners.com/salt-flats/"
   }},
   {"lat" : -16.171329, 
   "lon" : -68.230677, 
   "name" : "Condoriri, Bolivia",
   "country" : "068",
   "posts" : {
   	"Running" : "https://twosundowners.com/bolivia-running/"
   }},
   {"lat" : -16.163977,
   "lon" :  -69.086814, 
   "name" : "Copacabana, Bolivia",
   "country" : "068",
   "posts" : {
   	"Running" : "https://twosundowners.com/bolivia-running/"
   }},
   {"lat" : -15.848505, 
   "lon" : -70.021054, 
   "name" : "Puno, Peru",
   "country" : "604",
   "posts" : {
   	"NoStory" : ""
   }},
   {"lat" : -14.514655, 
   "lon" : -71.980451, 
   "name" : "Cusco, Peru",
   "country" : "604",
   "posts" : {
      "General" : "https://twosundowners.com/digital-nomad-cusco/",
      "Food" : "https://twosundowners.com/vegetarian-food-cusco/",
      "Running" : "https://twosundowners.com/running-in-cusco/"
      }},
   {"lat" : -13.156058, 
   "lon" : -73.926524, 
   "name" : "Salkantay & Machu Picchu, Peru",
   "country" : "604",
   "posts" : {
      "General" : "https://twosundowners.com/salkantay-trek/",
      "Gallery" : "https://twosundowners.com/photo-gallery/gallery/salkantay-machu-picchu/#album"
   }},
   {"lat" : -13.259986, 
   "lon" : -73.267283, 
   "name" : "Ollantaytambo, Peru",
   "country" : "604",
   "posts" : {
      "Guide" : "https://twosundowners.com/ollantaytambo/",
      "Gallery" : "https://twosundowners.com/photo-gallery/gallery/1769/#album",
      "Running" : "https://twosundowners.com/running-in-cusco/"
   }},
   {"lat" : -13.790552, 
   "lon" : -71.232811, 
   "name" : "Ausangate massif, Peru",
   "country" : "604",
   "posts" : {
      "General" : "https://twosundowners.com/ausangate-trek/",
      "Gallery" : "https://twosundowners.com/photo-gallery/gallery/ausangate-trek/#album"
   }},
   {"lat" : -12.106740, 
   "lon" : -72.045081, 
   "name" : "Lares, Peru",
   "country" : "604",
   "posts" : {}},
   {"lat" : -13.311414, 
   "lon" : -72.028161, 
   "name" : "Huaran, Peru",
   "country" : "604",
   "posts" : {
      "Guide" : "https://twosundowners.com/sacred-valley/",
      "Running" : "https://twosundowners.com/running-in-cusco/"
   }},
   {"lat" : -9.520975, 
   "lon" : -77.530068, 
   "name" : "Huaraz, Peru",
   "country" : "604",
   "posts" : {
      "General" : "https://twosundowners.com/huaraz/",
   }},
   {"lat" : -9.010320, 
   "lon" : -77.611996,
   "name" : "Laguna 69, Peru",
   "country" : "604",
   "posts" : {
      "General" : "https://twosundowners.com/laguna-69/",
      "Gallery" : "https://twosundowners.com/photo-gallery/gallery/peru-laguna-69/#album"
   }},
   {"lat" : 6.241829, 
   "lon" : -75.571250, 
   "name" : "Medellin, Colombia",
   "country" : "170",
   "posts" : {
      "Guide" : "https://twosundowners.com/10-things-medellin/",
      "General": "https://twosundowners.com/medellin/" 
   }},
   {"lat" : 6.231396, 
   "lon" : -75.158678, 
   "name" : "Guatape, Colombia",
   "country" : "170",
   "posts" : {
      "General" : "https://twosundowners.com/guatape/",
   }},
   {"lat" : 10.748722, 
   "lon" : -75.213978, 
   "name" : "Santa Marta, Colombia",
   "country" : "170",
   "posts" : {
      "General" : "https://twosundowners.com/santa-marta/",
   }},
   {"lat" : 10.412690, 
   "lon" : -75.537000, 
   "name" : "Cartagena, Colombia",
   "country" : "170",
   "posts" : {
      "General" : "https://twosundowners.com/cartagena/",
   }},
   {"lat" : 9.793243, 
   "lon" : -75.858449, 
   "name" : "Islas de San Bernardo, Colombia",
   "country" : "170",
   "posts" : {
      "General" : "https://twosundowners.com/casa-en-el-agua/",
   }},
   {"lat" : 4.618133, 
   "lon" : -74.070657 , 
   "name" : "Bogota, Colombia",
   "country" : "170",
   "posts" : {
      "General" : "https://twosundowners.com/bogota/",
   }},
   {"lat" : 11.288231, 
   "lon" : -74.151929, 
   "name" : "Tayrona National Park, Colombia",
   "country" : "170",
   "posts" : {
      "General" : "https://twosundowners.com/tayrona/",
   }},
   {"lat" : -33.438100, 
   "lon" : -71.658713, 
   "name" : "Santiago de Chile, Chile",
   "country" : "152",
   "posts" : {
      "General" : "https://twosundowners.com/santiago-de-chile/",
   }},
   {"lat" : -34.701668,
   "lon" :  -71.334896, 
   "name" : "Cajon de Maipo, Chile",
   "country" : "152",
   "posts" : {}},
   {"lat" : -33.043221,
   "lon" : -73.608303,
   "name" : "Valparaiso, Chile",
   "country" : "152",
   "posts" : {
      "General" : "https://twosundowners.com/valparaiso/",
   }},
   {"lat" : -33.853629, 
   "lon" : 149.239549, 
   "name" : "Sydney, Australia",
   "country" : "036",
   "posts" : {
       "Guide": "https://twosundowners.com/sydney/"
   }},
   {"lat" : -27.498027,
   "lon" : 150.998502, 
   "name" : "Brisbane, Australia",
   "country" : "036",
   "posts" : {}},
   {"lat" : -16.923840, 
   "lon" : 144.762937, 
   "name" : "Cairns, Australia",
   "country" : "036",
   "posts" : {
      "General": "https://twosundowners.com/queensland-road-trip/",
   }},
   {"lat" : -15.485735,
   "lon" : 144.464824, 
   "name" : "Port Douglas, Australia",
   "country" : "036",
   "posts" : {
      "General": "https://twosundowners.com/queensland-road-trip/",
   }},
   {"lat" : -14.170165, 
   "lon" : 144.418354, 
   "name" : "Daintree, Australia",
   "country" : "036",
   "posts" : {
      "General": "https://twosundowners.com/queensland-road-trip/",
      "Guide": "https://twosundowners.com/daintree-rainforest/"
   }},
   {"lat" : -28.594068, 
   "lon" : 151.224257, 
   "name" : "Nimbin, Australia",
   "country" : "036",
   "posts" : {}},
   {"lat" : -28.638879, 
   "lon" : 152.130533, 
   "name" : "Byron Bay, NSW",
   "country" : "036",
   "posts" : {}},
   {"lat" : -31.937407, 
   "lon" : 150.368654, 
   "name" : "Newcastle, NSW",
   "country" : "036",
   "posts" : {
       "General": "https://twosundowners.com/newcastle",
   }},
   {"lat" : -33.685930, 
   "lon" : 148.400717, 
   "name" : "Blue Mountains, NSW",
   "country" : "036",
   "posts" : {
       "General": "https://twosundowners.com/blue-mountains/",
   }},
   {"lat" : -35.232032, 
   "lon" : 145.377299, 
   "name" : "Bright, VIC",
   "country" : "036",
   "posts" : {
   	"Guide": "https://twosundowners.com/bright/"
   }},
   {"lat" : -37.217348, 
   "lon" : 144.531003, 
   "name" : "Melbourne, VIC",
   "country" : "036",
   "posts" : {
   	"Guide": "https://twosundowners.com/great-ocean-road/"
   }},
   {"lat" : -41.883346, 
   "lon" : 146.331346, 
   "name" : "Hobart, TAS",
   "country" : "036",
   "posts" : {}},
   {"lat" : -42.379406, 
   "lon" : 146.342117, 
   "name" : "Bruny Island, TAS",
   "country" : "036",
   "posts" : {
   	"General": "https://twosundowners.com/tasmania-tips/",
   }},
   {"lat" : -42.413413, 
   "lon" : 144.873841, 
   "name" : "Hastings Caves, TAS",
   "country" : "036",
   "posts" : {}},
   {"lat" : -40.730509, 
   "lon" : 146.912095 , 
   "name" : "Freycinet, TAS",
   "country" : "036",
   "posts" : {
   	"General": "https://twosundowners.com/tasmania-tips/",
   }},
   {"lat" : -43.117167,  
   "lon" : 145.840903,
   "name" : "Port Arthur, TAS",
   "country" : "036",
   "posts" : {
   	"General": "https://twosundowners.com/tasmania-tips/",
   }},
   {"lat" : -40.763768, 
   "lon" : 144.535420, 
   "name" : "Craddle Mountain, TAS",
   "country" : "036",
   "posts" : {
   	"General": "https://twosundowners.com/tasmania-tips/",
   }},
   {"lat" : -43.015038, 
   "lon" : 172.036583,
   "name" : "Christchurch, New Zealand",
   "country" : "554",
   "posts" : {}},
   {"lat" : -43.251586, 
   "lon" : 172.567542,
   "name" : "Le Bons Bay, New Zealand",
   "country" : "554",
   "posts" : {}},
   {"lat" : -41.468989, 
   "lon" : 172.688937, 
   "name" : "Nelson Lakes, New Zealand",
   "country" : "554",
   "posts" : {}},
   {"lat" : -42.104004, 
   "lon" : 170.842898, 
   "name" : "Punakaiki, New Zealand",
   "country" : "554",
   "posts" : {}},
   {"lat" : -44.277479, 
   "lon" : 169.201305, 
   "name" : "Makaroa, New Zealand",
   "country" : "554",
   "posts" : {}},
   {"lat" : -44.699580, 
   "lon" : 169.131977, 
   "name" : "Wanaka, New Zealand",
   "country" : "554",
   "posts" : {}},
   {"lat" : -45.034654, 
   "lon" : 168.666790, 
   "name" : "Queenstown, New Zealand",
   "country" : "554",
   "posts" : {}},
];


var visited_countries = ["752", "578", "703", "642", "100",
						 "008", "807", "070", "040", "604",
						 "068", "840", "276", "826", "-99", 
						 "499", "191", "170", "152", "036",
						 "554"];
						 
var post_cats = [{"name" : "General", 
				  "url" : "img/General.jpg"},
				 {"name" : "Guide" , 
				  "url" : "img/Guide.jpg"},
				 {"name" : "Running" , 
				  "url" : "img/Running.jpg"},
				 {"name" : "Food" , 
				  "url" : "img/Food.jpg"},
				 {"name" : "Climbing" , 
				  "url" : "img/Climbing.jpg"},
				 {"name" : "Nature" , 
				  "url" : "img/Nature.jpg"},
				 {"name" : "Gallery" , 
				  "url" : "img/Gallery.jpg"},
				  {"name" : "City" , 
				  "url" : "img/City.jpg"}];
				  
var icon_links = {"General" : "img/General.jpg",
				  "Guide" : "img/Guide.jpg",
				  "Running" : "img/Running.jpg",
				  "Food" : "img/Food.jpg",
				  "Climbing" : "img/Climbing.jpg",
				  "Nature" : "img/Nature.jpg",
				  "Gallery" : "img/Gallery.jpg",
				  "City" : "img/City.jpg",
				  "NoStory" : ""};