/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from 'three'
import React, { JSX, useRef, useState } from 'react'
import { Float, useGLTF, useTexture } from '@react-three/drei'
import { GLTF } from 'three-stdlib'
import gsap from "gsap";
import { useGSAP } from '@gsap/react'

gsap.registerPlugin(useGSAP);

type GLTFResult = GLTF & {
  nodes: {
    Cube: THREE.Mesh
  }
  materials: {}
}

export function Cube(
  {position, ...props}:
  {position?: THREE.Vector3, props?: JSX.IntrinsicElements['group']}
) {
  const { nodes, materials } = useGLTF('/models/cube.glb') as unknown as GLTFResult;

  const texture = useTexture('textures/cube.png');

  const cubeRef = useRef<THREE.Mesh>(null);
  const [hovered, setHovered] = useState<boolean>(false);

  useGSAP(() => {
    if(!cubeRef.current) return;
    console.log(cubeRef.current)
    gsap.timeline({
        repeat: -1,
        repeatDelay: 0.5,
      })
      .to(cubeRef.current.rotation, {
        y: hovered ? '+=2' : `+=${Math.PI * 2}`,
        x: hovered ? '+=2' : `-=${Math.PI * 2}`,
        duration: 2.5,
        stagger: {
          each: 0.15,
        },
      });
  });


  return (
    <Float floatIntensity={2}>
        <group {...props} position={[9, -4, 0]} rotation={[2.6, 0.8, -1.8]} scale={0.74} dispose={null}>
          <mesh
              ref={cubeRef}
              castShadow
              receiveShadow
              geometry={nodes.Cube.geometry}
              material={nodes.Cube.material}
              onPointerEnter={() => setHovered(true)}
              onPointerLeave={() => setHovered(false)}
          >
            <meshMatcapMaterial matcap={texture} toneMapped={false} />
          </mesh>
        </group>
    </Float>
  )
}

useGLTF.preload('/models/cube.glb')