/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: xenadus (https://sketchfab.com/xenadus)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/react-logo-76174ceeba96487f9863f974636f641e
Title: React logo
*/

import * as THREE from 'three'
import React, { JSX } from 'react'
import { Float, useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    ['React-Logo_Material002_0']: THREE.Mesh
  }
  materials: {
    ['Material.002']: THREE.MeshStandardMaterial
  }
}

export function ReactLogo({position, props}: {position?: THREE.Vector3, props?: JSX.IntrinsicElements['group']}) {
  const { nodes, materials } = useGLTF('/models/react.glb') as unknown as GLTFResult
  return (
    <Float floatIntensity={1}>
        <group {...props} dispose={null} position={[8, 7, 0]} scale={0.3}>
        <mesh
            castShadow
            receiveShadow
            geometry={nodes['React-Logo_Material002_0'].geometry}
            material={materials['Material.002']}
            position={[0, 0.079, 0.181]}
            rotation={[0, 0, -Math.PI / 2]}
            scale={[0.392, 0.392, 0.527]}
        />
        </group>
    </Float>
  )
}

useGLTF.preload('/models/react.glb')
